### ISSUE TITLE
OptiFabric 0.7.3 crashes with Fabric Loader 0.14.x

### ISSUE THREAD

**Issue by Sjouwer** [Sjouwer/OptiFabric-1.14.4-Updated#1]
On a fresh install Minecraft will crash with OptiFabric 0.7.3 and Fabric Loader 0.14.x
OptiFabric fails to create the mapped OptiFine jar which will cause Minecraft to crash with the error: ``Registering texture``
For now the solution is to install Fabric Loader 0.12.x or 0.13.x

**Comment by Cuturyeztwzudzuzrusxutdltxitrx5iex** [comment]
Luis
